- dashboards/dynamodb/dynamodb_table_dashboard.sp
- dashboards/dynamodb/dynamodb_table_report_age.sp
- dashboards/dynamodb/dynamodb_table_report_encryption.sp
This PR includes the following changes -
- Removal of unnecessary containers across the tables
- Addition of "ARN" as the hidden column
- Removal of encryption status from the dashboard since it does not five enough idea if a Dynamodb table is encrypted or not (by default all Dynamodb tables are encrypted)
> Update DynamoDB reports to the latest format

- dashboards/iam/iam_access_key_report_age.sp
- dashboards/iam/iam_credential_report.sp
- dashboards/iam/iam_group_dashboard.sp
- dashboards/iam/iam_group_detail.sp
- dashboards/iam/iam_role_dashboard.sp
- dashboards/iam/iam_role_detail.sp
- dashboards/iam/iam_role_report_full_administrative_privilege.sp
- dashboards/iam/iam_role_report_full_administrative_privileges.sp
- dashboards/iam/iam_root_access_report.sp
- dashboards/iam/iam_user_dashboard.sp
- dashboards/iam/iam_user_detail.sp
- dashboards/iam/iam_user_excessive_privilege_report.sp
- dashboards/iam/iam_user_mfa_report.sp
This includes fixes for default values that were left behind in the details page of role and group
> Update IAM reports to the latest format

- dashboards/sns/docs/sns_topic_detail.md
- dashboards/sns/sns_topic_detail.sp
- dashboards/sns/sns_topic_report_encryption.sp
> Add SNS detail page

- dashboards/iam/iam_user_dashboard.sp
- dashboards/kms/kms_key_dashboard.sp
- dashboards/lambda/lambda_function_dashboard.sp
- dashboards/rds/rds_db_cluster_dashboard.sp
- dashboards/rds/rds_db_cluster_snapshot_dashboard.sp
- dashboards/rds/rds_db_instance_dashboard.sp
- dashboards/rds/rds_db_instance_snapshot_dashboard.sp
- dashboards/redshift/redshift_cluster_dashboard.sp
- dashboards/s3/s3_bucket_dashboard.sp
- dashboards/sns/sns_topic_dashboard.sp
- dashboards/sqs/sqs_queue_dashboard.sp
- dashboards/vpc/vpc_dashboard.sp
> Add card links to IAM, KMS, Lambda, RDS, Redshift, S3, SNS, SQS and VPC dashboards

- mod.sp
> Add Steampipe CLI dependency to the mod.sp file

- dashboards/s3/docs/s3_bucket_detail.md
- dashboards/s3/s3_bucket_dashboard.sp
- dashboards/s3/s3_bucket_detail.sp
- dashboards/s3/s3_bucket_report_age.sp
- dashboards/s3/s3_bucket_report_encryption.sp
> Add the missing document references for S3 dashboard and reports closes #73

- mod.sp
> Update mod.sp with aws plugin required version

- dashboards/acm/acm_certificate_detail.sp
- dashboards/acm/docs/acm_certificate_detail.md
- dashboards/dynamodb/docs/dynamodb_table_detail.md
- dashboards/dynamodb/dynamodb_table_detail.sp
- dashboards/rds/docs/rds_db_cluster_snapshot_detail.md
- dashboards/rds/rds_db_cluster_snapshot_detail.sp
- dashboards/rds/rds_db_cluster_snapshot_report_age.sp
- dashboards/rds/rds_db_cluster_snapshot_report_encryption.sp
> Update doc files of detail dashboards

- dashboards/vpc/vpc_dashboard.sp
> Fix aws_vpc_empty_status query in aws_vpc_dashboard dashboard

- dashboards/redshift/docs/redshift_snapshot_detail.md
- dashboards/redshift/redshift_cluster_snapshot_detail.sp
> Add Redshift > Snapshot relationship graph

- dashboards/dynamodb/dynamodb_table_detail.sp
> Update to query format

- dashboards/vpc/docs/vpc_flow_log_detail.md
- dashboards/vpc/docs/vpc_subnet_detail.md
- dashboards/vpc/vpc_flow_log_detail.sp
- dashboards/vpc/vpc_subnet_detail.sp
> Add VPC Flow Log  & Subnet detail

- dashboards/lambda/lambda_function_detail.sp
- dashboards/sns/sns_topic_detail.sp
- dashboards/sqs/sqs_queue_detail.sp
> Update Lambda funtion, SNS topic and SQS queue relationship graphs edge categories

- dashboards/dynamodb/dynamodb_table_detail.sp
> Updates as per new format

- dashboards/base.sp
- dashboards/ecs/docs/ecs_service_detail.md
- dashboards/ecs/ecs_cluster_detail.sp
- dashboards/ecs/ecs_service_detail.sp
> Add ECS service relationship graph

- dashboards/ec2/ec2_instance_detail.sp
> Fixes issues in EC2 Detail

- dashboards/base.sp
- dashboards/ecs/docs/ecs_task_definition_detail.md
- dashboards/ecs/ecs_task_definition_detail.sp
> Add ECS Task Definition Detail

- dashboards/codecommit/codecommit.sp
- dashboards/codecommit/codecommit_repository_detail.sp
- dashboards/codecommit/docs/codecommit_repository_detail.md
- dashboards/eks/eks_cluster_detail.sp
> Add detail page for Codecommit Repository

- dashboards/codebuild/codebuild.sp
- dashboards/codebuild/codebuild_project_detail.sp
- dashboards/codebuild/docs/codebuild_project_detail.md
> Adds detail page for CodeBuild Project with relationship graph 

- dashboards/sqs/sqs_queue_detail.sp
> Updated  SQS > Queue Relationship graph

- dashboards/ebs/ebs_volume_dashboard.sp
- dashboards/ebs/ebs_volume_detail.sp
> Update aws_ebs_volume table queries to use the new format of the table

- mod.sp
> Update AWS plugin dependency to v0.80.0

- dashboards/api_gatewayv2/api_gatewayv2_api_dashboard.sp
- dashboards/api_gatewayv2/api_gatewayv2_api_detail.sp
- dashboards/api_gatewayv2/docs/api_gatewayv2_api_dashboard.md
> Add api_gatewayv2_api_dashboard

- dashboards/api_gatewayv2/api_gatewayv2_api_report_age.sp
- dashboards/api_gatewayv2/docs/api_gatewayv2_api_report_age.md
> Add api_gatewayv2_api_report_age

- dashboards/codecommit/codecommit_repository_age.sp
- dashboards/codecommit/codecommit_repository_dashboard.sp
- dashboards/codecommit/docs/codecommit_repository_dashboard.md
- dashboards/codecommit/docs/codecommit_repository_report_age.md
> Add AWS > Codecommit Repository Dashboard and Age Report

- dashboards/ecr/docs/ecr_repository_dashboard.md
- dashboards/ecr/docs/ecr_repository_report_age.md
- dashboards/ecr/ecr_repository_age_report.sp
- dashboards/ecr/ecr_repository_dashboard.sp
> Add AWS > ECR Repository dashboard & age report

- dashboards/redshift/redshift_cluster_detail.sp
> Add Redshift cluster and snapshot graph updates

- dashboards/cloudfront/cloudfront_distribution_dashboard.sp
- dashboards/cloudfront/docs/cloudfront_distribution_dashboard.md
> Add cloudfront_distribution_dashboard

- dashboards/emr/docs/emr_cluster_dashboard.md
- dashboards/emr/docs/emr_cluster_report_age.md
- dashboards/emr/emr_cluster_dashboard.sp
- dashboards/emr/emr_cluster_report_age.sp
> Add emr_cluster_dashboard and emr_cluster_report_age

- dashboards/backup/backup_plan_detail.sp
- dashboards/backup/backup_vault_detail.sp
- dashboards/categories.sp
- dashboards/dax/dax_cluster_detail.sp
- dashboards/dynamodb/dynamodb_table_detail.sp
> Update backup detail pages

- dashboards/dynamodb/dynamodb_table_detail.sp
>  Updated dynamodb detail page with with HCL implementation

- dashboards/ebs/ebs_volume_detail.sp
- dashboards/ec2/ec2_gateway_load_balancer_detail.sp
- dashboards/ec2/ec2_instance_detail.sp
- dashboards/ec2/ec2_network_interface_detail.sp
- dashboards/ecs/ecs_cluster_detail.sp
- dashboards/iam/iam.sp
- dashboards/iam/iam_role_detail.sp
- dashboards/vpc/vpc_detail.sp
- dashboards/vpc/vpc_eip_detail.sp
- dashboards/vpc/vpc_security_group_detail.sp
- dashboards/vpc/vpc_subnet_detail.sp
> Update ec2 instance detail page with HCL implementation

- dashboards/kms/kms_key_detail.sp
- dashboards/rds/rds_db_cluster_detail.sp
- dashboards/rds/rds_db_cluster_snapshot_detail.sp
- dashboards/rds/rds_db_instance_detail.sp
- dashboards/rds/rds_db_instance_snapshot_detail.sp
- dashboards/sns/sns_topic_detail.sp
- dashboards/vpc/vpc_detail.sp
- dashboards/vpc/vpc_security_group_detail.sp
- dashboards/vpc/vpc_subnet_detail.sp
> Update RDS Instance graph hcl

- dashboards/acm/acm_certificate_detail.sp
- dashboards/acm/acm_nodes.sp
- dashboards/cloudfront/cloudfront_distribution_detail.sp
- dashboards/cloudfront/cloudfront_nodes.sp
- dashboards/ec2/ec2_application_load_balancer_detail.sp
- dashboards/ec2/ec2_classic_load_balancer_detail.sp
- dashboards/ec2/ec2_network_load_balancer_detail.sp
- dashboards/opensearch/opensearch_nodes.sp
> Refactor ACM detail page

- dashboards/dynamodb/dynamodb_nodes.sp
- dashboards/dynamodb/dynamodb_table_detail.sp
- dashboards/kinesis/kinesis_nodes.sp
> Refactor DynamoDB table detail page > backup node

- dashboards/sqs/sqs_queue_detail.sp
> Fix AWS SQS Queue Detail dashboard to correctly check if the queue is encrypted by AWS Managed SQS keys closes #243

- dashboards/dax/dax.sp
- dashboards/dax/dax_cluster_detail.sp
- dashboards/dax/dax_edges.sp
- dashboards/dax/dax_nodes.sp
- dashboards/vpc/vpc_edges.sp
> Refactor dax cluster

- dashboards/acm/acm_certificate_detail.sp
- dashboards/api_gatewayv2/api_gatewayv2_api_detail.sp
- dashboards/cloudfront/cloudfront_distribution_detail.sp
- dashboards/dax/dax.sp
- dashboards/dax/dax_cluster_detail.sp
- dashboards/dynamodb/dynamodb_table_detail.sp
- dashboards/ebs/ebs_edges.sp
- dashboards/ebs/ebs_volume_detail.sp
- dashboards/ec2/ec2_instance_detail.sp
- dashboards/ec2/ec2_network_interface_detail.sp
> Sort node names, edge names, args, with blocks and category files

- dashboards/iam/iam.sp
- dashboards/iam/iam_group_detail.sp
- dashboards/iam/iam_policy_detail.sp
- dashboards/iam/iam_user_detail.sp
- dashboards/kms/kms_key_detail.sp
- dashboards/lambda/lambda_function_detail.sp
- dashboards/rds/rds_db_cluster_detail.sp
- dashboards/rds/rds_db_cluster_snapshot_detail.sp
- dashboards/rds/rds_db_instance_detail.sp
- dashboards/rds/rds_db_instance_snapshot_detail.sp
- dashboards/redshift/redshift_cluster_detail.sp
- dashboards/redshift/redshift_cluster_snapshot_detail.sp
- dashboards/s3/s3_bucket_detail.sp
- dashboards/sns/sns_topic_detail.sp
- dashboards/sqs/sqs_queue_detail.sp
- dashboards/vpc/vpc_detail.sp
- dashboards/vpc/vpc_eip_detail.sp
- dashboards/vpc/vpc_flow_logs_detail.sp
- dashboards/vpc/vpc_security_group_detail.sp
- dashboards/vpc/vpc_subnet_detail.sp
> Sort node names, edge names, category names, with blocks and args

- dashboards/rds/rds_db_instance_detail.sp
- dashboards/s3/s3_bucket_detail.sp
- dashboards/vpc/vpc_security_group_detail.sp
> Fix with block names

- dashboards/backup/backup_edges.sp
- dashboards/backup/backup_nodes.sp
- dashboards/backup/backup_plan_detail.sp
- dashboards/backup/backup_vault_detail.sp
- dashboards/kms/kms_key_detail.sp
- dashboards/kms/kms_nodes.sp
- dashboards/sns/sns_nodes.sp
- dashboards/sns/sns_topic_detail.sp
> Refactor backup_plan and backup_vault to new format

- dashboards/aws/aws.sp
- dashboards/ec2/ec2.sp
- dashboards/iam/iam.sp
- dashboards/iam/iam_nodes.sp
- dashboards/vpc/vpc.sp
> Add material icons

- dashboards/codebuild/codebuild_edges.sp
- dashboards/codebuild/codebuild_nodes.sp
- dashboards/codebuild/codebuild_project_detail.sp
- dashboards/codecommit/codecommit_nodes.sp
- dashboards/codecommit/codecommit_repository_detail.sp
- dashboards/ecr/ecr_repository_detail.sp
- dashboards/s3/s3_edges.sp
> Refactor codebuild_project to new format

- dashboards/codebuild/codebuild_edges.sp
- dashboards/codebuild/codebuild_project_detail.sp
- dashboards/codecommit/codecommit_edges.sp
- dashboards/codecommit/codecommit_repository_detail.sp
- dashboards/codepipeline/codepipeline_pipeline_detail.sp
> Refactor Codecommit Repository detail page

- dashboards/codebuild/codebuild_edges.sp
- dashboards/codecommit/codecommit_edges.sp
- dashboards/codedeploy/codedeploy_edges.sp
- dashboards/codedeploy/codedeploy_nodes.sp
- dashboards/codepipeline/codepipeline_edges.sp
- dashboards/codepipeline/codepipeline_nodes.sp
- dashboards/codepipeline/codepipeline_pipeline_detail.sp
- dashboards/ecr/ecr_edges.sp
- dashboards/iam/iam_edges.sp
- dashboards/kms/kms_key_edges.sp
- dashboards/s3/s3_edges.sp
> Refactor codepipeline_pipeline to new format

- dashboards/ec2/ec2_instance_detail.sp
- dashboards/ec2/ec2_nodes.sp
- dashboards/ecr/ecr_nodes.sp
- dashboards/ecs/ecs_cluster_detail.sp
- dashboards/ecs/ecs_edges.sp
- dashboards/ecs/ecs_nodes.sp
- dashboards/ecs/ecs_service_detail.sp
- dashboards/ecs/ecs_task_definition_detail.sp
- dashboards/efs/efs_nodes.sp
- dashboards/iam/iam_nodes.sp
- dashboards/vpc/vpc.sp
> Refactor ECS Cluster, Service, Task Definitions

- dashboards/eks/eks_cluster_detail.sp
- dashboards/eks/eks_edges.sp
- dashboards/eks/eks_nodes.sp
> Refactor eks_cluster to new format

- dashboards/ecr/ecr_edges.sp
- dashboards/ecr/ecr_nodes.sp
- dashboards/ecr/ecr_repository_detail.sp
- dashboards/ecs/ecs_nodes.sp
> Refactor ECR detail page

- dashboards/ecr/ecr_repository_detail.sp
- dashboards/elasticache/elasticache_cluster_detail.sp
- dashboards/elasticache/elasticache_edges.sp
- dashboards/elasticache/elasticache_nodes.sp
- dashboards/vpc/vpc_edges.sp
> Refactor elasticache_cluster to new format

- dashboards/api_gatewayv2/api_gatewayv2_api_detail.sp
- dashboards/ec2/ec2_application_load_balancer_detail.sp
- dashboards/ec2/ec2_classic_load_balancer_detail.sp
- dashboards/ec2/ec2_edges.sp
- dashboards/ec2/ec2_gateway_load_balancer_detail.sp
- dashboards/ec2/ec2_instance_detail.sp
- dashboards/ec2/ec2_load_balancer_nodes_edges.sp
- dashboards/ec2/ec2_network_load_balancer_detail.sp
- dashboards/ec2/ec2_nodes.sp
- dashboards/s3/s3_bucket_detail.sp
> Refactor load balancer graphs

- dashboards/ec2/ec2_application_load_balancer_detail.sp
- dashboards/ec2/ec2_classic_load_balancer_detail.sp
- dashboards/ec2/ec2_edges.sp
- dashboards/ec2/ec2_network_load_balancer_detail.sp
- dashboards/efs/efs_edges.sp
- dashboards/efs/efs_file_system_detail.sp
- dashboards/eks/eks_cluster_detail.sp
- dashboards/eks/eks_edges.sp
- dashboards/iam/iam_role_detail.sp
- dashboards/rds/rds_db_instance_detail.sp
- dashboards/rds/rds_edges.sp
- dashboards/redshift/redshift_cluster_detail.sp
- dashboards/redshift/redshift_edges.sp
- dashboards/s3/s3_bucket_detail.sp
- dashboards/s3/s3_edges.sp
- dashboards/sns/sns_edges.sp
- dashboards/sns/sns_topic_detail.sp
- dashboards/sqs/sqs_queue_detail.sp
- dashboards/vpc/vpc_detail.sp
- dashboards/vpc/vpc_edges.sp
- dashboards/vpc/vpc_flow_logs_detail.sp
- dashboards/vpc/vpc_nodes.sp
- dashboards/vpc/vpc_security_group_detail.sp
- dashboards/vpc/vpc_subnet_detail.sp
> Update formatting and sorting order

- dashboards/api_gatewayv2/api_gatewayv2_edges.sp
- dashboards/api_gatewayv2/api_gatewayv2_nodes.sp
- dashboards/cloudtrail/cloudtrail_edges.sp
- dashboards/cloudwatch/cloudwatch_edges.sp
- dashboards/cloudwatch/cloudwatch_log_group_detail.sp
- dashboards/codebuild/codebuild_edges.sp
- dashboards/codebuild/codebuild_project_detail.sp
- dashboards/codedeploy/codedeploy_edges.sp
- dashboards/codepipeline/codepipeline_edges.sp
- dashboards/codepipeline/codepipeline_pipeline_detail.sp
- dashboards/dax/dax_edges.sp
- dashboards/dax/dax_nodes.sp
- dashboards/dynamodb/dynamodb_edges.sp
- dashboards/dynamodb/dynamodb_nodes.sp
- dashboards/ebs/ebs_edges.sp
- dashboards/ebs/ebs_snapshot_detail.sp
- dashboards/ec2/ec2_application_load_balancer_detail.sp
- dashboards/ec2/ec2_edges.sp
- dashboards/ec2/ec2_gateway_load_balancer_detail.sp
- dashboards/ec2/ec2_instance_detail.sp
- dashboards/ec2/ec2_load_balancer_nodes_edges.sp
- dashboards/ec2/ec2_network_load_balancer_detail.sp
- dashboards/ecr/ecr_edges.sp
- dashboards/ecr/ecr_repository_detail.sp
- dashboards/ecs/ecs_cluster_detail.sp
- dashboards/ecs/ecs_edges.sp
- dashboards/ecs/ecs_nodes.sp
- dashboards/ecs/ecs_service_detail.sp
- dashboards/ecs/ecs_task_definition_detail.sp
> Update and sort to new format

- dashboards/backup/backup_edges.sp
- dashboards/ec2/ec2_edges.sp
- dashboards/ec2/ec2_gateway_load_balancer_detail.sp
- dashboards/efs/efs_edges.sp
- dashboards/efs/efs_nodes.sp
- dashboards/emr/emr_cluster_detail.sp
- dashboards/eventbridge/eventbribdge_edges.sp
- dashboards/guardduty/guardduty_edges.sp
- dashboards/iam/iam_edges.sp
- dashboards/kms/kms_key_detail.sp
- dashboards/lambda/lambda_function_detail.sp
- dashboards/rds/rds_edges.sp
- dashboards/rds/rds_nodes.sp
- dashboards/redshift/redshift_edges.sp
- dashboards/redshift/redshift_nodes.sp
- dashboards/s3/s3_edges.sp
- dashboards/vpc/vpc_detail.sp
- dashboards/vpc/vpc_edges.sp
- dashboards/vpc/vpc_nodes.sp
- dashboards/vpc/vpc_security_group_detail.sp
- dashboards/vpc/vpc_subnet_detail.sp
> Fix edges and update the detail pages

- dashboards/elasticache/elasticache_cluster_dashboard.sp
> Fix elasticache_cluster_cache_node_count query

- dashboards/cloudtrail/cloudtrail_trail_detail.sp
> CloudTrail Detail shows multiple trails in the 'overview' panel when using multi-region trails Closes #160

- dashboards/vpc/vpc_detail.sp
> Add missing network_interface node in vpc detail page

- dashboards/cloudfront/cloudfront_distribution_detail.sp
>  Fix & tidy up cloudfront_distribution_detail alias references

- dashboards/elasticache/docs/elasticache_replication_group_detail.md
- dashboards/elasticache/elasticache.sp
- dashboards/elasticache/elasticache_cluster_dashboard.sp
- dashboards/elasticache/elasticache_cluster_detail.sp
- dashboards/elasticache/elasticache_edges.sp
- dashboards/elasticache/elasticache_nodes.sp
- dashboards/elasticache/elasticache_replication_group_detail.sp
- dashboards/vpc/vpc_edges.sp
> Add elasticache_replication_node_detail

- dashboards/dax/dax_cluster_detail.sp
> Fix Dax Cluster Detail Page

- dashboards/iam/iam.sp
- dashboards/iam/iam_resource_policy.sp
- dashboards/lambda/lambda_function_detail.sp
- dashboards/s3/s3_bucket_detail.sp
- dashboards/sns/sns_topic_detail.sp
- dashboards/sqs/sqs_queue_detail.sp
> Resource policy graph

- dashboards/backup/backup_vault_detail.sp
- dashboards/ecr/ecr_repository_detail.sp
- dashboards/kms/kms_key_detail.sp
- dashboards/s3/s3_bucket_detail.sp
- dashboards/vpc/vpc_edges.sp
> Add Resource policy graph

- mod.sp
> Update the mod dependencies to use steampipe v0.18.0 and aws v0.91.0

- dashboards/rds/rds_db_instance_detail.sp
> Fix RDS DB Instance to correctly load VPC Security Group Closes #295

- dashboards/rds/rds_db_cluster_snapshot_dashboard.sp
> Fix rds_db_cluster_snapshot_dashboard by removing the incorrect `rds_db_cluster_snapshot_cost_mtd` query. Fixes #189

- dashboards/rds/rds_db_cluster_dashboard.sp
- dashboards/rds/rds_db_cluster_snapshot_dashboard.sp
- dashboards/rds/rds_db_instance_snapshot_dashboard.sp
> Remove cost queries from rds_db_cluster_snapshort_dashboard, rds_db_instance_snapshort_dashboard. Closes #306

- dashboards/acm/acm_certificate_report_age.sp
- dashboards/api_gatewayv2/api_gatewayv2_api_report_age.sp
- dashboards/codebuild/codebuild_project_report_age.sp
- dashboards/codecommit/codecommit_repository_age.sp
- dashboards/codecommit/codecommit_repository_report_age.sp
- dashboards/codepipeline/codepipeline_pipeline_report_age.sp
- dashboards/dynamodb/dynamodb_table_report_age.sp
- dashboards/ebs/ebs_snapshot_report_age.sp
- dashboards/ebs/ebs_volume_report_age.sp
- dashboards/ec2/ec2_instance_report_age.sp
- dashboards/ecr/ecr_repository_age_report.sp
- dashboards/efs/efs_file_system_report_age.sp
- dashboards/eks/eks_cluster_report_age.sp
- dashboards/elasticache/elasticache_cluster_node_report_age.sp
- dashboards/emr/emr_cluster_report_age.sp
- dashboards/iam/iam_access_key_report_age.sp
- dashboards/kms/kms_key_report_age.sp
- dashboards/rds/rds_db_cluster_report_age.sp
- dashboards/rds/rds_db_cluster_snapshot_report_age.sp
- dashboards/rds/rds_db_instance_report_age.sp
- dashboards/rds/rds_db_instance_snapshot_report_age.sp
- dashboards/redshift/redshift_cluster_report_age.sp
- dashboards/s3/s3_bucket_report_age.sp
> Update age report by sorting them according to creation date

- mod.sp
> Update mod.sp to address deprecation warning

- docs/index.md
> Fix index docs by removing unsupported images

- dashboards/opensearch/docs/opensearch_details.md
- dashboards/opensearch/opensearch.sp
- dashboards/opensearch/opensearch_details.sp
- dashboards/opensearch/opensearch_edges.sp
- dashboards/opensearch/opensearch_nodes.sp
> Add opensearch detail dashboard

- dashboards/ecs/ecs_cluster_dashboard.sp
> Fix ecs service query

- CHANGELOG.md
> Update CHANGELOG for v0.21

- dashboards/s3/s3_bucket_report_lifecycle.pp
> Add lifecycle_rules column to the s3_bucket_lifecycle_table closes #358
